export interface SampleProduct {
  _id: string;
  name: string;
  description: string;
  brand: string;
  category: string;
  price: number;
  salePrice: number;
  stock: number;
  sku: string;
  images: { public_id: string; url: string; alt: string }[];
  sizes: string[];
  colors: { name: string; hex: string }[];
  tags: string[];
  featured: boolean;
  isNewArrival: boolean;
  isTrending: boolean;
  isSale: boolean;
  ratings: number;
  numOfReviews: number;
  createdAt: string;
}

export const sampleProducts: SampleProduct[] = [
  {
    _id: '1',
    name: 'Premium Cotton T-Shirt',
    description: 'Crafted from 100% organic cotton with a relaxed fit. Perfect for everyday wear with exceptional comfort and breathability.',
    brand: 'OUTFITY',
    category: 'men',
    price: 2499,
    salePrice: 1799,
    stock: 50,
    sku: 'OFT-MEN-001',
    images: [
      { public_id: '1', url: 'bg-gradient-to-br from-stone-400 to-stone-600', alt: 'Premium Cotton T-Shirt Front' },
      { public_id: '2', url: 'bg-gradient-to-br from-stone-300 to-stone-500', alt: 'Premium Cotton T-Shirt Back' },
      { public_id: '3', url: 'bg-gradient-to-br from-stone-200 to-stone-400', alt: 'Premium Cotton T-Shirt Side' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#000000' }, { name: 'White', hex: '#FFFFFF' }, { name: 'Navy', hex: '#000080' }],
    tags: ['cotton', 'casual', 'premium'],
    featured: true,
    isNewArrival: true,
    isTrending: true,
    isSale: true,
    ratings: 4.5,
    numOfReviews: 128,
    createdAt: '2026-05-01T00:00:00Z',
  },
  {
    _id: '2',
    name: 'Classic Denim Jacket',
    description: 'Timeless denim jacket with a modern slim fit. Features signature branding and premium denim wash.',
    brand: 'OUTFITY',
    category: 'men',
    price: 5999,
    salePrice: 4499,
    stock: 35,
    sku: 'OFT-MEN-002',
    images: [
      { public_id: '1', url: 'bg-gradient-to-br from-blue-400 to-blue-700', alt: 'Classic Denim Jacket Front' },
      { public_id: '2', url: 'bg-gradient-to-br from-blue-300 to-blue-600', alt: 'Classic Denim Jacket Back' },
    ],
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [{ name: 'Blue', hex: '#0000FF' }, { name: 'Black', hex: '#000000' }],
    tags: ['denim', 'jacket', 'classic'],
    featured: true,
    isNewArrival: false,
    isTrending: true,
    isSale: true,
    ratings: 4.7,
    numOfReviews: 95,
    createdAt: '2026-04-15T00:00:00Z',
  },
  {
    _id: '3',
    name: 'Elegant Evening Dress',
    description: 'A stunning floor-length evening dress with delicate embroidery. Designed for special occasions.',
    brand: 'OUTFITY',
    category: 'women',
    price: 8999,
    salePrice: 6999,
    stock: 20,
    sku: 'OFT-WMN-001',
    images: [
      { public_id: '1', url: 'bg-gradient-to-br from-rose-400 to-rose-700', alt: 'Elegant Evening Dress Front' },
      { public_id: '2', url: 'bg-gradient-to-br from-rose-300 to-rose-600', alt: 'Elegant Evening Dress Back' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [{ name: 'Rose', hex: '#E0115F' }, { name: 'Black', hex: '#000000' }, { name: 'Navy', hex: '#000080' }],
    tags: ['evening', 'dress', 'elegant'],
    featured: true,
    isNewArrival: true,
    isTrending: true,
    isSale: true,
    ratings: 4.8,
    numOfReviews: 67,
    createdAt: '2026-05-10T00:00:00Z',
  },
  {
    _id: '4',
    name: 'Slim Fit Chinos',
    description: 'Modern slim-fit chinos crafted from stretch cotton twill. Comfort meets sophistication.',
    brand: 'OUTFITY',
    category: 'men',
    price: 3499,
    salePrice: 2499,
    stock: 45,
    sku: 'OFT-MEN-003',
    images: [
      { public_id: '1', url: 'bg-gradient-to-br from-khaki-400 to-khaki-700', alt: 'Slim Fit Chinos Front' },
    ],
    sizes: ['30', '32', '34', '36'],
    colors: [{ name: 'Beige', hex: '#D4C5A9' }, { name: 'Navy', hex: '#000080' }, { name: 'Black', hex: '#000000' }],
    tags: ['chinos', 'slim', 'casual'],
    featured: false,
    isNewArrival: false,
    isTrending: true,
    isSale: true,
    ratings: 4.3,
    numOfReviews: 156,
    createdAt: '2026-03-20T00:00:00Z',
  },
  {
    _id: '5',
    name: 'Cashmere Blend Sweater',
    description: 'Luxurious cashmere blend sweater with ribbed cuffs and hem. Ultra-soft and warm.',
    brand: 'OUTFITY',
    category: 'women',
    price: 6999,
    salePrice: 0,
    stock: 25,
    sku: 'OFT-WMN-002',
    images: [
      { public_id: '1', url: 'bg-gradient-to-br from-violet-400 to-violet-700', alt: 'Cashmere Blend Sweater' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Violet', hex: '#8B00FF' }, { name: 'Cream', hex: '#FFFDD0' }, { name: 'Gray', hex: '#808080' }],
    tags: ['cashmere', 'sweater', 'luxury'],
    featured: true,
    isNewArrival: true,
    isTrending: false,
    isSale: false,
    ratings: 4.6,
    numOfReviews: 89,
    createdAt: '2026-05-05T00:00:00Z',
  },
  {
    _id: '6',
    name: 'Leather Crossbody Bag',
    description: 'Handcrafted genuine leather crossbody bag with adjustable strap and multiple compartments.',
    brand: 'OUTFITY',
    category: 'accessories',
    price: 4999,
    salePrice: 3999,
    stock: 30,
    sku: 'OFT-ACC-001',
    images: [
      { public_id: '1', url: 'bg-gradient-to-br from-amber-600 to-amber-900', alt: 'Leather Crossbody Bag' },
    ],
    sizes: ['One Size'],
    colors: [{ name: 'Brown', hex: '#8B4513' }, { name: 'Black', hex: '#000000' }],
    tags: ['leather', 'bag', 'accessories'],
    featured: false,
    isNewArrival: true,
    isTrending: true,
    isSale: true,
    ratings: 4.4,
    numOfReviews: 112,
    createdAt: '2026-05-08T00:00:00Z',
  },
  {
    _id: '7',
    name: 'Running Performance Shoes',
    description: 'Lightweight performance running shoes with responsive cushioning and breathable mesh upper.',
    brand: 'OUTFITY',
    category: 'footwear',
    price: 7999,
    salePrice: 5999,
    stock: 40,
    sku: 'OFT-FTW-001',
    images: [
      { public_id: '1', url: 'bg-gradient-to-br from-emerald-400 to-emerald-700', alt: 'Running Performance Shoes' },
    ],
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: [{ name: 'Green', hex: '#008000' }, { name: 'Black', hex: '#000000' }, { name: 'White', hex: '#FFFFFF' }],
    tags: ['running', 'shoes', 'performance'],
    featured: true,
    isNewArrival: false,
    isTrending: true,
    isSale: true,
    ratings: 4.9,
    numOfReviews: 203,
    createdAt: '2026-04-01T00:00:00Z',
  },
  {
    _id: '8',
    name: 'Kids Colorful Hoodie',
    description: 'Fun and comfortable hoodie for kids with vibrant colors and soft fleece lining.',
    brand: 'OUTFITY',
    category: 'kids',
    price: 1999,
    salePrice: 1499,
    stock: 60,
    sku: 'OFT-KID-001',
    images: [
      { public_id: '1', url: 'bg-gradient-to-br from-yellow-300 to-orange-500', alt: 'Kids Colorful Hoodie' },
    ],
    sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y'],
    colors: [{ name: 'Yellow', hex: '#FFD700' }, { name: 'Blue', hex: '#0000FF' }, { name: 'Red', hex: '#FF0000' }],
    tags: ['kids', 'hoodie', 'casual'],
    featured: false,
    isNewArrival: true,
    isTrending: false,
    isSale: true,
    ratings: 4.2,
    numOfReviews: 74,
    createdAt: '2026-05-12T00:00:00Z',
  },
];

export const categories = [
  { name: 'Men', slug: 'men', image: 'bg-gradient-to-br from-stone-500 to-stone-800', description: 'Premium apparel for men' },
  { name: 'Women', slug: 'women', image: 'bg-gradient-to-br from-rose-400 to-rose-700', description: 'Elegant fashion for women' },
  { name: 'Kids', slug: 'kids', image: 'bg-gradient-to-br from-yellow-400 to-orange-600', description: 'Playful styles for kids' },
  { name: 'Footwear', slug: 'footwear', image: 'bg-gradient-to-br from-emerald-500 to-emerald-800', description: 'Shoes for every occasion' },
  { name: 'Bags', slug: 'bags', image: 'bg-gradient-to-br from-amber-600 to-amber-900', description: 'Bags & accessories' },
  { name: 'Accessories', slug: 'accessories', image: 'bg-gradient-to-br from-violet-500 to-violet-800', description: 'Complete your look' },
];

export const reviews = [
  {
    _id: 'r1',
    user: { _id: 'u1', name: 'Priya Sharma', avatar: '' },
    product: '1',
    rating: 5,
    comment: 'Absolutely love this t-shirt! The fabric is incredibly soft and the fit is perfect. Definitely worth every penny.',
    images: [],
    isApproved: true,
    createdAt: '2026-05-15T00:00:00Z',
  },
  {
    _id: 'r2',
    user: { _id: 'u2', name: 'Rahul Verma', avatar: '' },
    product: '1',
    rating: 4,
    comment: 'Great quality denim jacket. The material is durable and the stitching is excellent. Slightly large fit, so size down.',
    images: [],
    isApproved: true,
    createdAt: '2026-05-10T00:00:00Z',
  },
  {
    _id: 'r3',
    user: { _id: 'u3', name: 'Ananya Patel', avatar: '' },
    product: '1',
    rating: 5,
    comment: 'The evening dress is stunning! Wore it to a wedding and received so many compliments. The embroidery is beautiful.',
    images: [],
    isApproved: true,
    createdAt: '2026-05-08T00:00:00Z',
  },
  {
    _id: 'r4',
    user: { _id: 'u4', name: 'Vikram Singh', avatar: '' },
    product: '1',
    rating: 4,
    comment: 'Comfortable chinos with great stretch. Perfect for office wear. Color matches as shown in pictures.',
    images: [],
    isApproved: true,
    createdAt: '2026-05-05T00:00:00Z',
  },
  {
    _id: 'r5',
    user: { _id: 'u5', name: 'Neha Gupta', avatar: '' },
    product: '1',
    rating: 5,
    comment: 'The cashmere sweater is pure luxury! So soft and warm. Already ordering another color.',
    images: [],
    isApproved: true,
    createdAt: '2026-05-01T00:00:00Z',
  },
];
